main:
  ENABLE: true
perm:
  USE_COMMAND: 'bcdonate.use'
settings:
  COLSOLE_ONLY: true
msg:
  MESSAGE: '&2BCDonate &8» &fPlayer &6%player% &fdonated to &6%donate%'
  NO_PERMISSION: '&2BCDonate &8» &fYou have no permission.'
  USAGE: '&2BCDonate &8» &fUsage: &6/bcdonate <player>'